blank_issues_enabled: false
contact_links:
  - name: How to contribute guide
    url: https://eskridd.github.io/PiPedia/#/How-to-Contribute
    about: Formatting help and the different ways to add articles.
